### ISSUE TITLE
issue

### ISSUE THREAD

**Issue by 1852097949** [AsprinChina/EnergyCircuitTheory-EnergyFlowCalculation#4]
老师，您文献中阀门模型是
![image](https://user-images.githubusercontent.com/124783268/222655832-d161af4e-bfec-4283-8cca-eae051f7bd5b.png)
但是在程序里面写成平方了
![屏幕截图 2023-03-03 150927](https://user-images.githubusercontent.com/124783268/222655624-2095eedb-d3fd-4315-9806-96c5168a9c43.jpg)

**Comment by Aspirin96** [comment]
谢谢，此bug已被修复
